"""Prepare an engine commandlet that checks every dialogue's Python key and Sound.

Run before build.ps1, then DevInstall/System/ucc.exe
UnatcoContinues.UCVoiceCheckCommandlet. No API calls or audio generation.
"""
from pathlib import Path

from make_voices import SRC, extract


def main():
    lines = extract()
    source = [
        '// Generated by tools/voices/prepare_voice_check.py.',
        '// Runs the compiled UnrealScript lookup against the audio package.',
        'class UCVoiceCheckCommandlet extends Commandlet;',
        '',
        'var int checked, failed;',
        '',
        'function Check(int expected, string speaker, string text, bool bRadio)',
        '{',
        '    local int actual;',
        '    local Sound snd;',
        '    checked++;',
        "    actual = class'UCVoice'.static.VoiceKey(speaker, text, bRadio);",
        "    snd = class'UCVoice'.static.Find(text, speaker, bRadio);",
        '    if (actual != expected || snd == None)',
        '    {',
        '        failed++;',
        '        Log("UCVoiceCheck FAIL expected=V" $ expected $ " actual=V" $ actual $ " sound=" $ snd);',
        '    }',
        '}',
        '',
        'function int Main(string Parms)',
        '{',
    ]
    for line in lines:
        text = line['text'].replace('\\', '\\\\').replace('"', '\\"')
        radio = 'True' if line['kind'] == 'infolink' and line['speaker'] != 'JCDenton' else 'False'
        source.append('    Check(%s, "%s", "%s", %s);' % (line['key'][1:], line['speaker'], text, radio))
    source += [
        '    Log("UCVoiceCheck: " $ checked $ " checked, " $ failed $ " failed.");',
        '    if (failed != 0)',
        '        return 1;',
        '    return 0;',
        '}',
        '',
        'defaultproperties',
        '{',
        '    HelpCmd="UCVoiceCheck"',
        '    HelpOneLiner="Check dialogue hashes and load all mod voice Sounds"',
        '    LazyLoad=False',
        '    ShowBanner=False',
        '}',
        '',
    ]
    path = Path(SRC) / 'UCVoiceCheckCommandlet.uc'
    path.write_text('\n'.join(source), encoding='utf-8')
    print('Prepared engine checks for %d dialogue lines: %s' % (len(lines), path))


if __name__ == '__main__':
    main()
